-- Local Atlas core schema upgrade.
-- Project-owned tables use the required `mlp_` prefix.
-- Existing public.mylocalplace rows are preserved by renaming the table to
-- public.mlp_mylocalplace when the prefixed table does not already exist.

create extension if not exists pgcrypto;

do $$
begin
  if to_regclass('public.mlp_mylocalplace') is null
     and to_regclass('public.mylocalplace') is not null then
    alter table public.mylocalplace rename to mlp_mylocalplace;
  end if;

  if to_regclass('public.mlp_profiles') is null
     and to_regclass('public.profiles') is not null then
    alter table public.profiles rename to mlp_profiles;
  end if;

  if to_regclass('public.mlp_capsule_discoveries') is null
     and to_regclass('public.capsule_discoveries') is not null then
    alter table public.capsule_discoveries rename to mlp_capsule_discoveries;
  end if;

  if to_regclass('public.mlp_capsule_reports') is null
     and to_regclass('public.capsule_reports') is not null then
    alter table public.capsule_reports rename to mlp_capsule_reports;
  end if;
end;
$$;

create table if not exists public.mlp_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null default 'Explorer',
  avatar_url text,
  energy integer not null default 100 check (energy between 0 and 100),
  master_keys integer not null default 3 check (master_keys >= 0),
  is_pro boolean not null default false,
  subscription_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mlp_mylocalplace (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  lat double precision not null,
  lng double precision not null,
  title text not null,
  hint text,
  difficulty smallint default 3,
  access_limit integer default 5,
  category text default '🧩 기타 아지트',
  user_id uuid,
  is_promoted boolean default false
);

alter table public.mlp_mylocalplace
  add column if not exists access_count integer not null default 0,
  add column if not exists unlock_radius_meters integer not null default 50,
  add column if not exists updated_at timestamptz not null default now();

update public.mlp_mylocalplace
   set access_count = coalesce(access_count, 0),
       unlock_radius_meters = coalesce(unlock_radius_meters, 50),
       updated_at = coalesce(updated_at, created_at, now()),
       hint = coalesce(hint, ''),
       difficulty = coalesce(difficulty, 3),
       access_limit = coalesce(access_limit, 5),
       category = coalesce(category, '🧩 기타 아지트'),
       is_promoted = coalesce(is_promoted, false);

create table if not exists public.mlp_capsule_discoveries (
  id uuid primary key default gen_random_uuid(),
  capsule_id bigint not null references public.mlp_mylocalplace(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  distance_meters numeric(10, 2) not null,
  created_at timestamptz not null default now(),
  unique (capsule_id, user_id)
);

create table if not exists public.mlp_capsule_reports (
  id uuid primary key default gen_random_uuid(),
  capsule_id bigint not null references public.mlp_mylocalplace(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  detail text,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

create index if not exists idx_mlp_mylocalplace_visible_created
  on public.mlp_mylocalplace (is_promoted, created_at desc);

create index if not exists idx_mlp_mylocalplace_owner_created
  on public.mlp_mylocalplace (user_id, created_at desc);

create index if not exists idx_mlp_capsule_discoveries_user_created
  on public.mlp_capsule_discoveries (user_id, created_at desc);

create index if not exists idx_mlp_capsule_discoveries_capsule_created
  on public.mlp_capsule_discoveries (capsule_id, created_at desc);

create or replace function public.mlp_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists mlp_profiles_touch_updated_at on public.mlp_profiles;
drop trigger if exists profiles_touch_updated_at on public.mlp_profiles;
create trigger mlp_profiles_touch_updated_at
before update on public.mlp_profiles
for each row execute function public.mlp_touch_updated_at();

drop trigger if exists mlp_mylocalplace_touch_updated_at on public.mlp_mylocalplace;
drop trigger if exists mylocalplace_touch_updated_at on public.mlp_mylocalplace;
create trigger mlp_mylocalplace_touch_updated_at
before update on public.mlp_mylocalplace
for each row execute function public.mlp_touch_updated_at();

create or replace function public.mlp_handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.mlp_profiles (id, nickname)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'nickname', ''),
      split_part(new.email, '@', 1),
      'Explorer'
    )
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.mlp_handle_new_user();

create or replace function public.mlp_distance_meters(
  lat_a double precision,
  lng_a double precision,
  lat_b double precision,
  lng_b double precision
)
returns double precision
language sql
immutable
as $$
  select 6371000 * 2 * asin(
    sqrt(
      power(sin(radians((lat_b - lat_a) / 2)), 2) +
      cos(radians(lat_a)) *
      cos(radians(lat_b)) *
      power(sin(radians((lng_b - lng_a) / 2)), 2)
    )
  );
$$;

drop function if exists public.verify_and_unlock(double precision, double precision, uuid);
drop function if exists public.verify_and_unlock(double precision, double precision, bigint);
drop function if exists public.mlp_verify_and_unlock(double precision, double precision, bigint);

create or replace function public.mlp_verify_and_unlock(
  u_lat double precision,
  u_lng double precision,
  target_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  target public.mlp_mylocalplace%rowtype;
  distance double precision;
  already_unlocked boolean;
  unlock_rank integer;
begin
  if current_user_id is null then
    return jsonb_build_object('ok', false, 'code', 'AUTH_REQUIRED', 'message', '로그인이 필요합니다.');
  end if;

  select *
    into target
    from public.mlp_mylocalplace
   where id = target_id
     and (
       is_promoted = true
       or user_id = current_user_id
       or user_id is null
       or exists (
         select 1
           from public.mlp_capsule_discoveries
          where capsule_id = target_id
            and user_id = current_user_id
       )
     );

  if not found then
    return jsonb_build_object('ok', false, 'code', 'NOT_FOUND', 'message', '열람할 수 없는 아지트입니다.');
  end if;

  distance := public.mlp_distance_meters(u_lat, u_lng, target.lat, target.lng);

  if distance > coalesce(target.unlock_radius_meters, 50) then
    return jsonb_build_object(
      'ok', false,
      'code', 'TOO_FAR',
      'message', '아직 충분히 가까이 가지 않았습니다.',
      'distance_meters', round(distance::numeric, 2),
      'required_meters', coalesce(target.unlock_radius_meters, 50)
    );
  end if;

  select exists (
    select 1
      from public.mlp_capsule_discoveries
     where capsule_id = target.id
       and user_id = current_user_id
  ) into already_unlocked;

  if coalesce(target.access_count, 0) >= coalesce(target.access_limit, 5) and not already_unlocked then
    return jsonb_build_object(
      'ok', false,
      'code', 'ACCESS_LIMIT_REACHED',
      'message', '선착순 열람 가능 인원이 모두 찼습니다.'
    );
  end if;

  if not already_unlocked then
    insert into public.mlp_capsule_discoveries (capsule_id, user_id, distance_meters)
    values (target.id, current_user_id, round(distance::numeric, 2));

    update public.mlp_mylocalplace
       set access_count = coalesce(access_count, 0) + 1
     where id = target.id;
  end if;

  select count(*)
    into unlock_rank
    from public.mlp_capsule_discoveries
   where capsule_id = target.id
     and created_at <= (
       select created_at
         from public.mlp_capsule_discoveries
        where capsule_id = target.id
          and user_id = current_user_id
     );

  return jsonb_build_object(
    'ok', true,
    'code', 'UNLOCKED',
    'title', target.title,
    'hint', coalesce(target.hint, ''),
    'distance_meters', round(distance::numeric, 2),
    'rank', unlock_rank,
    'already_unlocked', already_unlocked
  );
end;
$$;

alter table public.mlp_profiles enable row level security;
alter table public.mlp_mylocalplace enable row level security;
alter table public.mlp_capsule_discoveries enable row level security;
alter table public.mlp_capsule_reports enable row level security;

drop policy if exists "mlp_profiles_select_owner" on public.mlp_profiles;
create policy "mlp_profiles_select_owner"
on public.mlp_profiles for select
to authenticated
using (id = auth.uid());

drop policy if exists "mlp_profiles_insert_owner" on public.mlp_profiles;
create policy "mlp_profiles_insert_owner"
on public.mlp_profiles for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "mlp_profiles_update_owner" on public.mlp_profiles;
create policy "mlp_profiles_update_owner"
on public.mlp_profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "mlp_capsules_select_visible" on public.mlp_mylocalplace;
create policy "mlp_capsules_select_visible"
on public.mlp_mylocalplace for select
to authenticated
using (
  is_promoted = true
  or user_id = auth.uid()
  or user_id is null
  or exists (
    select 1
      from public.mlp_capsule_discoveries
     where capsule_id = public.mlp_mylocalplace.id
       and user_id = auth.uid()
  )
);

drop policy if exists "mlp_capsules_insert_owner" on public.mlp_mylocalplace;
create policy "mlp_capsules_insert_owner"
on public.mlp_mylocalplace for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "mlp_capsules_update_owner" on public.mlp_mylocalplace;
create policy "mlp_capsules_update_owner"
on public.mlp_mylocalplace for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "mlp_capsules_delete_owner" on public.mlp_mylocalplace;
create policy "mlp_capsules_delete_owner"
on public.mlp_mylocalplace for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "mlp_discoveries_select_owner" on public.mlp_capsule_discoveries;
create policy "mlp_discoveries_select_owner"
on public.mlp_capsule_discoveries for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "mlp_discoveries_insert_owner" on public.mlp_capsule_discoveries;

drop policy if exists "mlp_reports_insert_owner" on public.mlp_capsule_reports;
create policy "mlp_reports_insert_owner"
on public.mlp_capsule_reports for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "mlp_reports_select_owner" on public.mlp_capsule_reports;
create policy "mlp_reports_select_owner"
on public.mlp_capsule_reports for select
to authenticated
using (user_id = auth.uid());

grant select (
  id,
  nickname,
  avatar_url,
  energy,
  master_keys,
  is_pro,
  subscription_end,
  created_at,
  updated_at
) on public.mlp_profiles to authenticated;

grant update (
  nickname,
  avatar_url,
  updated_at
) on public.mlp_profiles to authenticated;

grant select (
  id,
  capsule_id,
  user_id,
  distance_meters,
  created_at
) on public.mlp_capsule_discoveries to authenticated;

grant select (
  id,
  capsule_id,
  user_id,
  reason,
  detail,
  status,
  created_at
) on public.mlp_capsule_reports to authenticated;

grant insert (
  capsule_id,
  user_id,
  reason,
  detail
) on public.mlp_capsule_reports to authenticated;

grant execute on function public.mlp_verify_and_unlock(double precision, double precision, bigint) to authenticated;

-- Keep hidden messages off regular client reads. The app receives `hint`
-- only from mlp_verify_and_unlock after the server-side distance check succeeds.
revoke select on public.mlp_mylocalplace from anon, authenticated;
grant select (
  id,
  user_id,
  title,
  category,
  lat,
  lng,
  difficulty,
  access_limit,
  access_count,
  unlock_radius_meters,
  is_promoted,
  created_at,
  updated_at
) on public.mlp_mylocalplace to authenticated;

grant insert (
  user_id,
  title,
  hint,
  category,
  lat,
  lng,
  difficulty,
  access_limit
) on public.mlp_mylocalplace to authenticated;

grant update (
  title,
  hint,
  category,
  difficulty,
  access_limit,
  unlock_radius_meters,
  updated_at
) on public.mlp_mylocalplace to authenticated;

grant delete on public.mlp_mylocalplace to authenticated;
grant usage, select on all sequences in schema public to authenticated;
